/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bankaccount;

import org.junit.jupiter.api.Test;

import bankaccount.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.getGreeting(), "Hello World!");
    }

}
